OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-3.5-turbo"
NEO4J_URI = "bolt://184.73.74.56:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "battleship-lives-clamps"